// <auto-generated />
using System;
using FlowBoard.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FlowBoard.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260621153227_AddProjectMembers")]
    partial class AddProjectMembers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FlowBoard.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid")
                        .HasColumnName("aggregate_id");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("aggregate_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("event_type");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_outbox_unprocessed")
                        .HasFilter("processed_at IS NULL");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("FlowBoard.Modules.Identity.Domain.Aggregates.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<bool>("IsEmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_email_verified");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password_hash");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("FlowBoard.Modules.Organisations.Domain.Aggregates.Organisation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_organisations");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_organisations_active")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_organisations_owner_id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_organisations_slug");

                    b.ToTable("organisations", null, t =>
                        {
                            t.HasCheckConstraint("chk_organisations_name", "char_length(name) BETWEEN 2 AND 100");

                            t.HasCheckConstraint("chk_organisations_slug", "slug ~ '^[a-z0-9-]+$'");
                        });
                });

            modelBuilder.Entity("FlowBoard.Modules.Projects.Domain.Aggregates.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organisation_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_projects_active")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("OrganisationId")
                        .HasDatabaseName("ix_projects_organisation_id");

                    b.HasIndex("OrganisationId", "Status")
                        .HasDatabaseName("ix_projects_organisation_id_status")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("projects", null, t =>
                        {
                            t.HasCheckConstraint("chk_projects_name", "char_length(name) BETWEEN 1 AND 150");

                            t.HasCheckConstraint("chk_projects_status", "status IN ('active', 'archived')");
                        });
                });

            modelBuilder.Entity("FlowBoard.Modules.Organisations.Domain.Aggregates.Organisation", b =>
                {
                    b.OwnsMany("FlowBoard.Modules.Organisations.Domain.Entities.Invitation", "Invitations", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime?>("AcceptedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("accepted_at");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<DateTime>("ExpiresAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("expires_at");

                            b1.Property<Guid>("InvitedById")
                                .HasColumnType("uuid")
                                .HasColumnName("invited_by_id");

                            b1.Property<string>("InvitedEmail")
                                .IsRequired()
                                .HasMaxLength(254)
                                .HasColumnType("character varying(254)")
                                .HasColumnName("invited_email");

                            b1.Property<Guid>("OrganisationId")
                                .HasColumnType("uuid")
                                .HasColumnName("organisation_id");

                            b1.Property<string>("Role")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("role");

                            b1.Property<string>("TokenHash")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("token_hash");

                            b1.HasKey("Id")
                                .HasName("pk_invitations");

                            b1.HasIndex("InvitedEmail")
                                .HasDatabaseName("ix_invitations_email");

                            b1.HasIndex("OrganisationId")
                                .HasDatabaseName("ix_invitations_organisation_id");

                            b1.HasIndex("TokenHash")
                                .IsUnique()
                                .HasDatabaseName("ix_invitations_token_hash");

                            b1.HasIndex("OrganisationId", "ExpiresAt")
                                .HasDatabaseName("ix_invitations_pending")
                                .HasFilter("accepted_at IS NULL");

                            b1.ToTable("invitations", null, t =>
                                {
                                    t.HasCheckConstraint("chk_invitations_role", "role IN ('admin', 'member', 'guest')");
                                });

                            b1.WithOwner()
                                .HasForeignKey("OrganisationId")
                                .HasConstraintName("fk_invitations_organisations_organisation_id");
                        });

                    b.OwnsMany("FlowBoard.Modules.Organisations.Domain.Entities.Membership", "Memberships", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid?>("InvitedById")
                                .HasColumnType("uuid")
                                .HasColumnName("invited_by_id");

                            b1.Property<DateTime>("JoinedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("joined_at");

                            b1.Property<Guid>("OrganisationId")
                                .HasColumnType("uuid")
                                .HasColumnName("organisation_id");

                            b1.Property<string>("Role")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("role");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid")
                                .HasColumnName("user_id");

                            b1.HasKey("Id")
                                .HasName("pk_memberships");

                            b1.HasIndex("OrganisationId")
                                .HasDatabaseName("ix_memberships_organisation_id");

                            b1.HasIndex("UserId")
                                .HasDatabaseName("ix_memberships_user_id");

                            b1.HasIndex("OrganisationId", "Role")
                                .HasDatabaseName("ix_memberships_organisation_id_role");

                            b1.HasIndex("UserId", "OrganisationId")
                                .IsUnique()
                                .HasDatabaseName("ix_memberships_user_id_organisation_id");

                            b1.ToTable("memberships", null, t =>
                                {
                                    t.HasCheckConstraint("chk_memberships_role", "role IN ('owner', 'admin', 'member', 'guest')");
                                });

                            b1.WithOwner()
                                .HasForeignKey("OrganisationId")
                                .HasConstraintName("fk_memberships_organisations_organisation_id");
                        });

                    b.Navigation("Invitations");

                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("FlowBoard.Modules.Projects.Domain.Aggregates.Project", b =>
                {
                    b.OwnsMany("FlowBoard.Modules.Projects.Domain.Entities.ProjectMember", "Members", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime>("AddedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("added_at");

                            b1.Property<Guid>("ProjectId")
                                .HasColumnType("uuid")
                                .HasColumnName("project_id");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid")
                                .HasColumnName("user_id");

                            b1.HasKey("Id")
                                .HasName("pk_project_members");

                            b1.HasIndex("ProjectId")
                                .HasDatabaseName("ix_project_members_project_id");

                            b1.HasIndex("UserId")
                                .HasDatabaseName("ix_project_members_user_id");

                            b1.HasIndex("ProjectId", "UserId")
                                .IsUnique()
                                .HasDatabaseName("ix_project_members_project_id_user_id");

                            b1.ToTable("project_members", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ProjectId")
                                .HasConstraintName("fk_project_members_projects_project_id");
                        });

                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
