<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\FlowBoard.Modules.Identity.Application\FlowBoard.Modules.Identity.Application.csproj" />
    <ProjectReference Include="..\..\..\FlowBoard.Infrastructure\FlowBoard.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
